SDK     := external/orion-sdk
COMM_I  := $(SDK)/Communications
UTIL_I  := $(SDK)/Utils
COMM_L  := $(SDK)/Communications/x86
UTIL_L  := $(SDK)/Utils/x86

COMM_LIB := $(COMM_L)/libOrionComm.a
UTIL_LIB := $(UTIL_L)/libOrionUtils.a

CC      ?= gcc
CFLAGS  ?= -O2 -Wall -Wextra -std=c99 -D_GNU_SOURCE
CPPFLAGS = -I$(COMM_I) -I$(UTIL_I)
LDFLAGS  = -L$(COMM_L) -L$(UTIL_L)
LDLIBS   = -Wl,--start-group -lOrionComm -lOrionUtils -Wl,--end-group -lm -lpthread

# Windows (MinGW/MSYS2): the SDK's Types.h checks WIN32, not _WIN32, so we
# need to define it explicitly. Also link ws2_32 for winsock symbols pulled in
# by libOrionComm.
ifeq ($(OS),Windows_NT)
CPPFLAGS += -DWIN32
LDLIBS   += -lws2_32 -liphlpapi
# OrionCommWindows.c:124 calls POSIX close() on a SOCKET (upstream bug).
# Redefine for the SDK Communications build only; the file's other socket
# closes already use closesocket(). OrionCommLinux.c is __linux__-guarded
# so it compiles to nothing here and is unaffected by this rename.
SDK_COMM_CFLAGS := -Dclose=closesocket
endif

SRC     := $(wildcard src/*.c)
OBJ     := $(SRC:.c=.o)
HDR     := $(wildcard src/*.h)
BIN     := orionctl

.PHONY: all clean test sdk sdk-clean sdk-check

all: $(BIN)

# Guard: fail with a useful message if the submodule isn't initialized.
# Sentinel is OrionPublicProtocol.xml (shipped in the SDK repo); the .c/.h pair
# next to it is code-generated by `make build` in Communications/.
sdk-check:
	@if [ ! -f $(SDK)/Communications/OrionPublicProtocol.xml ]; then \
		echo "error: $(SDK) is empty. Initialize the submodule:"; \
		echo "  git submodule update --init --recursive"; \
		exit 1; \
	fi

# Build the SDK libs on demand. Utils consumes generated headers from
# Communications, so order matters. SDK_COMM_CFLAGS is set per-platform
# above; it's appended (via common.mk's `CFLAGS+=`) to the SDK's defaults.
$(COMM_LIB): | sdk-check
	$(MAKE) -C $(SDK)/Communications build CFLAGS="$(SDK_COMM_CFLAGS)"

$(UTIL_LIB): $(COMM_LIB)
	$(MAKE) -C $(SDK)/Utils build

sdk: $(COMM_LIB) $(UTIL_LIB)

# orionctl sources include SDK headers (some generated), so .o files have an
# order-only dep on the libs being built first. The blanket $(HDR) dep is
# conservative -- any header change forces a full recompile -- which is the
# right default because shared structs like octl_ctx_t change layout.
src/%.o: src/%.c $(HDR) | $(COMM_LIB) $(UTIL_LIB)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

$(BIN): $(OBJ) $(COMM_LIB) $(UTIL_LIB)
	$(CC) $(CFLAGS) $(CPPFLAGS) $(OBJ) -o $@ $(LDFLAGS) $(LDLIBS)

tests/test_fov_math: tests/test_fov_math.c src/fov_math.c src/fov_math.h
	$(CC) $(CFLAGS) -I src tests/test_fov_math.c src/fov_math.c -o $@ -lm

test: tests/test_fov_math
	@./tests/test_fov_math

sdk-clean:
	-$(MAKE) -C $(SDK)/Communications clean
	-$(MAKE) -C $(SDK)/Utils clean

clean:
	rm -f $(OBJ) $(BIN) tests/*.o tests/test_*
